baseURL = ''
languageCode = 'en-us'
title = 'ECWUUUUU'
theme = 'ecwu-theme'

[params]
  subtitle = "ECWU's Notebook"
  # copyright = "(c) Zhenghao Wu, Some Rights reserved."
  copyrightHolder = "ECWU"
  showPoweredBy = true
  showBeian = true
  beianMessage = " 粤 ICP 备 17015575 号 - 1"
  homePageThought = 'Hi, <a href="/page/about">Jack Wu (a.k.a ECWU)</a> here. The blog may contain random thoughts, technological content, projects, and photography work. Other than that, I have a site <a href="https://ecwu.xyz">(ECWU.xyz)</a> storing my random stuff.'

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'solarized-dark'
    tabWidth = 2

[frontmatter]
  date = ['date', 'publishDate']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod']
  publishDate = ['publishDate', 'date']

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------

[[menu.nav]]
  name = "Home"
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Posts"
  weight = -100 
  identifier = "posts"
  url = "/post/"
[[menu.nav]]
  name = "Photos"
  weight = -90 
  identifier = "photos"
  url = "/photography/"
[[menu.nav]]
  name = "Topics"
  weight = -80 
  identifier = "topics"
  url = "/topic/"
[[menu.nav]]
  name = "About"
  weight = -60 
  identifier = "about"
  url = "/page/about/"
[[menu.nav]]
  name = "Friends"
  weight = -50
  identifier = "friends"
  url = "/page/friends/"

[[menu.topic]]
  name = "Projects"
  pre = "School work and Personal"
  weight = -100
  identifier = "projects"
  url = "/project/"
[[menu.topic]]
  name = "Keep List"
  pre = "List of stuffs I enjoy"
  weight = -90
  identifier = "keeplist"
  url = "/page/keep/"
