baseURL = ''
languageCode = 'en-us'
timeZone = "Asia/Shanghai"
title = 'ECWUUUUU'
theme = 'ecwu-theme'


enableGitInfo = true
hasCJKLanguage = true
footnoteReturnLinkContents = '↩'

[params]
  subtitle = "ECWU's Notebook"
  copyrightHolder = "ECWU"
  showPoweredBy = true
  showBeian = true
  beianMessage = " 粤 ICP 备 17015575 号 - 1"
  homePageThought = 'Hi, <a href="/page/about">Jack Wu (a.k.a ECWU)</a> here. The blog may contain random thoughts, technological content, projects, and photography work. Other than that, I have a site <a href="https://ecwu.xyz">(ECWU.xyz)</a> storing my random stuff.'
  email = "ecwu@protonmail.com"
  github = "ecwu"
  google_scholar = "gBi_1mgAAAAJ"
  linkedin = "zhenghaowu"
  instagram = "ecwu"
  video = "https://space.bilibili.com/509461"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'solarized-dark'
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[frontmatter]
  date = ['date', 'publishDate']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod']
  publishDate = ['publishDate', 'date']


[related]
  includeNewer = false
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'category'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80
[[related.indices]]
  name = 'date'
  weight = 10

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------

[[menu.nav]]
  name = "Home"
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Posts"
  weight = -100 
  identifier = "posts"
  url = "/post/"
[[menu.nav]]
  name = "Photos"
  weight = -90 
  identifier = "photos"
  url = "/photography/"
[[menu.nav]]
  name = "Series"
  weight = -80 
  identifier = "topics"
  url = "/series/"
[[menu.nav]]
  name = "About"
  weight = -60 
  identifier = "about"
  url = "/page/about/"
[[menu.nav]]
  name = "Friends"
  weight = -50
  identifier = "friends"
  url = "/page/friends/"

[[menu.topic]]
  name = "Projects"
  pre = "School work and Personal"
  weight = -100
  identifier = "projects"
  url = "/project/"
[[menu.topic]]
  name = "Keep List"
  pre = "List of stuffs I enjoy"
  weight = -90
  identifier = "keeplist"
  url = "/page/keep/"
