baseurl = "https://ecwuuuuu.com/"
# baseurl = "/"
languageCode = "en"
title = "Σ<VV⋃"
theme = "hugo-tufte"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true


[params]
  subtitle = "ECWU's Notebook"
  # copyright = "(c) Zhenghao Wu, Some Rights reserved."
  copyrightHolder = "ECWU"
  showPoweredBy = true
  showBeian = true
  beianMessage = "粤 ICP 备 17015575 号 - 1"

[taxonomies]
  category = "categories" 
  tag = "tags"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[markup.goldmark.renderer]
unsafe= true

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  pre = "<i class='fa fa-home fa-lg'></i> "
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Posts"
  pre = "<i class='fa fa-book fa-lg'></i> "
  weight = -100 
  identifier = "posts"
  url = "/post"
[[menu.nav]]
  name = "Photography"
  pre = "<i class='fa fa-camera-retro fa-lg'></i> "
  weight = -90 
  identifier = "photography"
  url = "/photography"
[[menu.nav]]
  name = "Project"
  pre = "<i class='fa fa-file-text-o fa-lg'></i> "
  weight = -80 
  identifier = "project"
  url = "/project"
[[menu.nav]]
  name = "Keep List"
  pre = "<i class='fa fa-paperclip fa-lg'></i> "
  weight = -70 
  identifier = "keep"
  url = "/page/keep"
[[menu.nav]]
  name = "About"
  pre = "<i class='fa fa-user fa-lg'></i> "
  weight = -60 
  identifier = "about"
  url = "/page/about"
[[menu.nav]]
  name = "Friends"
  pre = "<i class='fa fa-users fa-lg'></i> "
  weight = -50
  identifier = "friends"
  url = "/page/friends"

# -----------------------------------------------------------------------
# Footer menu 
# -----------------------------------------------------------------------
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-github fa-2x'></i> "
  weight = -100 
  identifier = "github"
  url = "https://github.com/ecwu"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-book fa-2x'></i> "
  weight = -90 
  identifier = "researchgate"
  url = "https://www.researchgate.net/profile/Zhenghao_Wu2"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-linkedin-square fa-2x'></i> "
  weight = -80 
  identifier = "linkedin"
  url = "https://www.linkedin.com/in/zhenghaowu/"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-instagram fa-2x'></i> "
  weight = -70
  identifier = "instagram"
  url = "https://www.instagram.com/ecwuuuuu/"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-video-camera fa-2x'></i> "
  weight = -60
  identifier = "bilibili"
  url = "https://space.bilibili.com/509461"